# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      payload:
        description: "The payload that includes information on the deploymnet."
        required: true
      runtime:
        description: "Runtime name (e.g node | bun)"
        default: "node"
        required: false
      runtime_version:
        description: "Runtime version (e.g. 18)"
        default: "18"
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      STORMKIT_APP_SECRET: ${{ secrets.STORMKIT_APP_SECRET }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        if: ${{ github.event.inputs.runtime == 'node' }}
        with:
          node-version: ${{github.event.inputs.runtime_version}}
      - uses: oven-sh/setup-bun@v1
        if: ${{ github.event.inputs.runtime == 'bun' }}

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Prepare folder structure
        run: mkdir -p repo dist

      - name: Run deployer service
        id: run_deployer
        if: always()
        run: ./runner --payload '${{ github.event.inputs.payload }}' --root-dir '${{github.workspace}}'
        timeout-minutes: 15
